/*
 * Copyright 2021 jrealsense project
 * 
 * Website: https://github.com/lambdaprime/jrealsense
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Authors:
 * - lambdaprime <intid@protonmail.com>
 */
/**
 * <p>Contains all JNI wrapping generated by SWIG for librealsense native library.</p>
 * 
 * <p><b>jrealsense</b> is built around this low level functions and hides them under
 * more convenient Java API. Some functionality may not be available through
 * <b>jrealsense</b> API yet but then it is possible to use librealsense functions
 * through this package directly.</p>
 * 
 * 
 */
package id.jrealsense.jni;
