/**
 * <p>Contains all JNI wrapping generated by SWIG for librealsense native library.</p>
 * 
 * <p><b>jrealsense</b> is built around this low level functions and hides them under
 * more convenient Java API. Some functionality may not be available through
 * <b>jrealsense</b> API yet but then it is possible to use librealsense functions
 * through this package directly.</p>
 * 
 * 
 */
package id.jrealsense.jni;
